/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author AST
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    private int mousePX, mousePY;
    
    public LoginScreen() {
        initComponents();
        
        //setting window screen
        this.setSize(1600,900);
        this.setLocationRelativeTo(null);
        
        //setting background color
        jPanelExitBar.setBackground(new Color(255, 255, 255, 20));
        jTextFieldUser.setBackground(new Color(255,255,255,200));
        jPasswordFieldPass.setBackground(new Color(255,255,255,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelExitBar = new javax.swing.JPanel();
        jLabelLoginExit = new javax.swing.JLabel();
        jLabelLoginMinimize = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jLabelLoginBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanelExitBar.setBackground(new java.awt.Color(44, 62, 80));
        jPanelExitBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelExitBarMouseDragged(evt);
            }
        });
        jPanelExitBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelExitBarMousePressed(evt);
            }
        });

        jLabelLoginExit.setFont(new java.awt.Font("Viner Hand ITC", 0, 36)); // NOI18N
        jLabelLoginExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoginExit.setText("X");
        jLabelLoginExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginExitMouseClicked(evt);
            }
        });

        jLabelLoginMinimize.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        jLabelLoginMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoginMinimize.setText("-");
        jLabelLoginMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelExitBarLayout = new javax.swing.GroupLayout(jPanelExitBar);
        jPanelExitBar.setLayout(jPanelExitBarLayout);
        jPanelExitBarLayout.setHorizontalGroup(
            jPanelExitBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExitBarLayout.createSequentialGroup()
                .addContainerGap(1546, Short.MAX_VALUE)
                .addComponent(jLabelLoginExit)
                .addGap(31, 31, 31))
            .addGroup(jPanelExitBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExitBarLayout.createSequentialGroup()
                    .addContainerGap(1494, Short.MAX_VALUE)
                    .addComponent(jLabelLoginMinimize)
                    .addGap(82, 82, 82)))
        );
        jPanelExitBarLayout.setVerticalGroup(
            jPanelExitBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLoginExit, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
            .addGroup(jPanelExitBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExitBarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelLoginMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 59, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanelExitBar);
        jPanelExitBar.setBounds(0, 0, 1600, 70);

        jLabelLogin.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogin.setText("LOGIN");
        getContentPane().add(jLabelLogin);
        jLabelLogin.setBounds(690, 160, 161, 78);

        jLabelUser.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUser.setText("Username :");
        getContentPane().add(jLabelUser);
        jLabelUser.setBounds(580, 270, 200, 59);

        jLabelPass.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabelPass.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPass.setText("Password  :");
        getContentPane().add(jLabelPass);
        jLabelPass.setBounds(580, 350, 200, 59);
        getContentPane().add(jTextFieldUser);
        jTextFieldUser.setBounds(790, 280, 210, 40);

        jPasswordFieldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPassActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldPass);
        jPasswordFieldPass.setBounds(790, 360, 210, 40);

        jLabelLoginBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/LoginScreen.png"))); // NOI18N
        jLabelLoginBg.setText("jLabel4");
        getContentPane().add(jLabelLoginBg);
        jLabelLoginBg.setBounds(0, 0, 1620, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelLoginExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginExitMouseClicked
        //closing window
        System.exit(0);
    }//GEN-LAST:event_jLabelLoginExitMouseClicked

    private void jLabelLoginMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMinimizeMouseClicked
        //minimizing window
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelLoginMinimizeMouseClicked

    private void jPasswordFieldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPassActionPerformed

    private void jPanelExitBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExitBarMouseDragged
       
        //setting screen location according to mouse pointer
        int coordinateX = evt.getXOnScreen();
        int coordinateY = evt.getYOnScreen();
        
        this.setLocation(coordinateX-mousePX,coordinateY-mousePY);
    }//GEN-LAST:event_jPanelExitBarMouseDragged

    private void jPanelExitBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExitBarMousePressed
        
        //getting coordinates of mouse pointer
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_jPanelExitBarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLoginBg;
    private javax.swing.JLabel jLabelLoginExit;
    private javax.swing.JLabel jLabelLoginMinimize;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanelExitBar;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
