/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

/**
 *
 * @author Atiqur Rahman
 */
public class RegisterScreen extends javax.swing.JFrame {

    /**
     * Creates new form RegisterScreen
     */
    private String fn, ln, pass, conpass, un, secques, secans, em;
    boolean flag, flagPass;
    boolean[] ara = new boolean[6];

    public RegisterScreen() {
        initComponents();
        this.setSize(1600, 900);
        this.setLocationRelativeTo(null);
        for (int i = 0; i < 6; i++) {
            ara[i] = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        securityAnswer = new javax.swing.JTextField();
        confirmPassward = new javax.swing.JTextField();
        securityQuestion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelconpass = new javax.swing.JLabel();
        jLabelpass = new javax.swing.JLabel();
        jLabelun = new javax.swing.JLabel();
        passward = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        jLabelpassMatch = new javax.swing.JLabel();
        jLabelfn = new javax.swing.JLabel();
        jLabelln = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabelem = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Security Answer");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 670, 350, 40);

        jLabel3.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 180, 240, 40);

        jLabel5.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 250, 240, 40);

        jLabel6.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 320, 240, 40);

        securityAnswer.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        securityAnswer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        securityAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityAnswerActionPerformed(evt);
            }
        });
        getContentPane().add(securityAnswer);
        securityAnswer.setBounds(670, 660, 330, 50);

        confirmPassward.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        confirmPassward.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmPassward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswardActionPerformed(evt);
            }
        });
        getContentPane().add(confirmPassward);
        confirmPassward.setBounds(670, 520, 330, 50);

        securityQuestion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        securityQuestion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        securityQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(securityQuestion);
        securityQuestion.setBounds(670, 590, 330, 50);

        jLabel7.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-Mail");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 390, 240, 40);

        jLabel8.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Passward");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 460, 240, 40);

        jLabel9.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm Passward");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 520, 360, 50);

        jLabel10.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Security Question");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 600, 380, 40);

        jLabel11.setFont(new java.awt.Font("Siyam Rupali", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("*");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1010, 530, 20, 30);

        jLabel12.setFont(new java.awt.Font("Siyam Rupali", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("*");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1010, 180, 20, 30);

        jLabel13.setFont(new java.awt.Font("Siyam Rupali", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("*");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1010, 250, 20, 30);

        jLabel14.setFont(new java.awt.Font("Siyam Rupali", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("*");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1010, 320, 20, 30);

        jLabel15.setFont(new java.awt.Font("Siyam Rupali", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("*");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1010, 390, 20, 30);

        jLabel16.setFont(new java.awt.Font("Siyam Rupali", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("*");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1010, 460, 20, 30);

        jLabelconpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelconpass.setForeground(new java.awt.Color(255, 51, 51));
        jLabelconpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelconpass);
        jLabelconpass.setBounds(1070, 520, 140, 30);

        jLabelpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelpass.setForeground(new java.awt.Color(255, 51, 51));
        jLabelpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelpass);
        jLabelpass.setBounds(1070, 450, 140, 30);

        jLabelun.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelun.setForeground(new java.awt.Color(255, 51, 51));
        jLabelun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelun);
        jLabelun.setBounds(1070, 310, 140, 30);

        passward.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        passward.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwardActionPerformed(evt);
            }
        });
        getContentPane().add(passward);
        passward.setBounds(670, 450, 330, 50);

        registerButton.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        registerButton.setText("OK");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton);
        registerButton.setBounds(700, 770, 170, 50);

        jLabelpassMatch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelpassMatch.setForeground(new java.awt.Color(255, 0, 0));
        jLabelpassMatch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelpassMatch);
        jLabelpassMatch.setBounds(650, 730, 290, 30);

        jLabelfn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelfn.setForeground(new java.awt.Color(255, 51, 51));
        jLabelfn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelfn);
        jLabelfn.setBounds(1070, 174, 140, 30);

        jLabelln.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelln.setForeground(new java.awt.Color(255, 51, 51));
        jLabelln.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelln);
        jLabelln.setBounds(1070, 240, 140, 30);

        email.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(670, 380, 330, 50);

        jLabelem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelem.setForeground(new java.awt.Color(255, 51, 51));
        jLabelem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelem);
        jLabelem.setBounds(1070, 380, 140, 30);

        userName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        getContentPane().add(userName);
        userName.setBounds(670, 310, 330, 50);

        lastName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        getContentPane().add(lastName);
        lastName.setBounds(670, 240, 330, 50);

        firstName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        firstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        getContentPane().add(firstName);
        firstName.setBounds(670, 170, 330, 50);

        jLabel2.setFont(new java.awt.Font("Unispace", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(670, 50, 300, 80);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JFrame/LoginScreen.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, 4, 1630, 900);
        jLabel1.getAccessibleContext().setAccessibleName("jLebel1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        fn = firstName.getText();
        ara[0] = true;
    }//GEN-LAST:event_firstNameActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        ln = lastName.getText();
        ara[1] = true;
    }//GEN-LAST:event_lastNameActionPerformed

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        un = userName.getText();
        ara[2] = true;
    }//GEN-LAST:event_userNameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        em = email.getText();
        ara[3] = true;
    }//GEN-LAST:event_emailActionPerformed

    private void passwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwardActionPerformed
        pass = passward.getText();
        ara[4] = true;
    }//GEN-LAST:event_passwardActionPerformed

    private void confirmPasswardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswardActionPerformed
        conpass = confirmPassward.getText();
        ara[5] = true;
    }//GEN-LAST:event_confirmPasswardActionPerformed

    private void securityQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityQuestionActionPerformed
        secques = securityQuestion.getText();
    }//GEN-LAST:event_securityQuestionActionPerformed

    private void securityAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityAnswerActionPerformed
        secans = securityAnswer.getText();
    }//GEN-LAST:event_securityAnswerActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        flag = false;
        for (int i = 1; i <= 6; i++) {
            if (ara[i - 1] == false) {
                if (i == 1) {
                    jLabelfn.setText("Must filled");
                } else if (i == 2) {
                    jLabelln.setText("Must filled");
                } else if (i == 3) {
                    jLabelun.setText("Must filled");
                } else if (i == 4) {
                    jLabelem.setText("Must filled");
                } else if (i == 5) {
                    jLabelpass.setText("Must filled");
                } else if (i == 6) {
                    jLabelconpass.setText("Must filled");
                }
                flag = true;
            }
            if (ara[i - 1] == true) {
                if (i == 1) {
                    jLabelfn.setText("");
                } else if (i == 2) {
                    jLabelln.setText("");
                } else if (i == 3) {
                    jLabelun.setText("");
                } else if (i == 4) {
                    jLabelem.setText("");
                } else if (i == 5) {
                    jLabelpass.setText("");
                } else if (i == 6) {
                    jLabelconpass.setText("");
                }
            }
        }
        if (flag == false) {
            if (pass != null && conpass != null) {
                if (pass.equals(conpass) == false) {
                    System.out.println("Failed");
                    jLabelpassMatch.setText("Passward doesn't match");
                } else {
                    jLabelpassMatch.setText("");
                    System.out.println("Successfull");
                }
            }
        } else {
            System.out.println("Failed");
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmPassward;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelconpass;
    private javax.swing.JLabel jLabelem;
    private javax.swing.JLabel jLabelfn;
    private javax.swing.JLabel jLabelln;
    private javax.swing.JLabel jLabelpass;
    private javax.swing.JLabel jLabelpassMatch;
    private javax.swing.JLabel jLabelun;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField passward;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField securityAnswer;
    private javax.swing.JTextField securityQuestion;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
