/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

/**
 *
 * @author Atiqur Rahman
 */
public class RegisterScreen extends javax.swing.JFrame {

    /**
     * Creates new form RegisterScreen
     */
    private String firstName = null, lastName = null, password = null, confirmPassword = null, userName = null, securityQuestion = null, securityAnswer = null, email = null;
    
    boolean flag, flagPass;
    boolean[] ara = new boolean[6];

    public RegisterScreen() {
        initComponents();
        this.setSize(450, 939);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSecurityAnswer = new javax.swing.JLabel();
        securityAnswerTextField = new javax.swing.JTextField();
        jLabelSecurityQuestion = new javax.swing.JLabel();
        securityQuestionTextField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        jLabelConfirmPassward = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelPassward = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelemail = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabelUserName = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        jLabelLastName = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        jLabelFirstName = new javax.swing.JLabel();
        SignupPanelBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(378, 1000));
        getContentPane().setLayout(null);

        jLabelSecurityAnswer.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelSecurityAnswer.setForeground(new java.awt.Color(120, 120, 120));
        jLabelSecurityAnswer.setText("Security Answer");
        getContentPane().add(jLabelSecurityAnswer);
        jLabelSecurityAnswer.setBounds(70, 670, 330, 60);

        securityAnswerTextField.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        securityAnswerTextField.setForeground(new java.awt.Color(255, 255, 255));
        securityAnswerTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        securityAnswerTextField.setBorder(null);
        securityAnswerTextField.setOpaque(false);
        securityAnswerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityAnswerTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(securityAnswerTextField);
        securityAnswerTextField.setBounds(70, 680, 330, 40);

        jLabelSecurityQuestion.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelSecurityQuestion.setForeground(new java.awt.Color(120, 120, 120));
        jLabelSecurityQuestion.setText("Security Question");
        getContentPane().add(jLabelSecurityQuestion);
        jLabelSecurityQuestion.setBounds(70, 590, 330, 60);

        securityQuestionTextField.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        securityQuestionTextField.setForeground(new java.awt.Color(255, 255, 255));
        securityQuestionTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        securityQuestionTextField.setBorder(null);
        securityQuestionTextField.setOpaque(false);
        securityQuestionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityQuestionTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(securityQuestionTextField);
        securityQuestionTextField.setBounds(70, 600, 330, 40);

        registerButton.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/signupButton.png"))); // NOI18N
        registerButton.setBorder(null);
        registerButton.setBorderPainted(false);
        registerButton.setContentAreaFilled(false);
        registerButton.setFocusPainted(false);
        registerButton.setFocusable(false);
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton);
        registerButton.setBounds(90, 760, 280, 130);

        jLabelConfirmPassward.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelConfirmPassward.setForeground(new java.awt.Color(120, 120, 120));
        jLabelConfirmPassward.setText("Confirm Passward");
        getContentPane().add(jLabelConfirmPassward);
        jLabelConfirmPassward.setBounds(70, 510, 330, 60);

        jPasswordField1.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPasswordField1.setBorder(null);
        jPasswordField1.setOpaque(false);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(70, 520, 330, 40);

        jLabelPassward.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelPassward.setForeground(new java.awt.Color(120, 120, 120));
        jLabelPassward.setText("Passward");
        getContentPane().add(jLabelPassward);
        jLabelPassward.setBounds(70, 430, 330, 60);

        jPasswordField.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPasswordField.setBorder(null);
        jPasswordField.setOpaque(false);
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField);
        jPasswordField.setBounds(70, 440, 330, 40);

        jLabelemail.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelemail.setForeground(new java.awt.Color(120, 120, 120));
        jLabelemail.setText("E-Mail");
        getContentPane().add(jLabelemail);
        jLabelemail.setBounds(70, 350, 330, 60);

        emailField.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        emailField.setForeground(new java.awt.Color(255, 255, 255));
        emailField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        emailField.setBorder(null);
        emailField.setOpaque(false);
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField);
        emailField.setBounds(70, 360, 330, 40);

        jLabelUserName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(120, 120, 120));
        jLabelUserName.setText("User Name");
        getContentPane().add(jLabelUserName);
        jLabelUserName.setBounds(70, 270, 330, 60);

        userNameField.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        userNameField.setForeground(new java.awt.Color(255, 255, 255));
        userNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userNameField.setBorder(null);
        userNameField.setOpaque(false);
        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(userNameField);
        userNameField.setBounds(70, 280, 330, 40);

        jLabelLastName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelLastName.setForeground(new java.awt.Color(120, 120, 120));
        jLabelLastName.setText("Last Name");
        getContentPane().add(jLabelLastName);
        jLabelLastName.setBounds(70, 190, 330, 60);

        lastNameTextField.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        lastNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        lastNameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lastNameTextField.setBorder(null);
        lastNameTextField.setOpaque(false);
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(lastNameTextField);
        lastNameTextField.setBounds(70, 200, 330, 40);

        firstNameTextField.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        firstNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        firstNameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        firstNameTextField.setBorder(null);
        firstNameTextField.setOpaque(false);
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(firstNameTextField);
        firstNameTextField.setBounds(70, 120, 330, 40);

        jLabelFirstName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelFirstName.setForeground(new java.awt.Color(120, 120, 120));
        jLabelFirstName.setText("First Name");
        jLabelFirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFirstNameMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelFirstName);
        jLabelFirstName.setBounds(70, 110, 330, 60);

        SignupPanelBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/signupPanelBg.png"))); // NOI18N
        getContentPane().add(SignupPanelBg);
        SignupPanelBg.setBounds(0, 0, 450, 939);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
            jLabelFirstName.setText("");
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed

    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed

    }//GEN-LAST:event_userNameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed

    }//GEN-LAST:event_emailFieldActionPerformed

    private void securityQuestionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityQuestionTextFieldActionPerformed

    }//GEN-LAST:event_securityQuestionTextFieldActionPerformed

    private void securityAnswerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityAnswerTextFieldActionPerformed

    }//GEN-LAST:event_securityAnswerTextFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        flag = false;
        firstName = firstNameTextField.getText();
        lastName = lastNameTextField.getText();
        userName = userNameField.getText();
        email = emailField.getText();
        securityQuestion = securityQuestionTextField.getText();
        securityAnswer = securityAnswerTextField.getText();
        password = jPasswordField.getText();
        confirmPassword = jPasswordField1.getText();
        //if(!firstName.isEmpty())
            //jLabelFirstName.setText("");
            
        
    }//GEN-LAST:event_registerButtonActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed

    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jLabelFirstNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFirstNameMouseClicked
        
    }//GEN-LAST:event_jLabelFirstNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignupPanelBg;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabelConfirmPassward;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelPassward;
    private javax.swing.JLabel jLabelSecurityAnswer;
    private javax.swing.JLabel jLabelSecurityQuestion;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField securityAnswerTextField;
    private javax.swing.JTextField securityQuestionTextField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
