/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import SnakeGame.music.MusicPlayer;
import SnakeGame.boards.SnakeBoard;
import SnakeGame.screens.MapEditor;
import SnakeGame.Options;
import SnakeGame.States;
import SnakeGame.boards.MapBoard;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author Lassassin
 */
public class SnakeGameMainMenu extends javax.swing.JFrame {

    public static SnakeBoard SNAKE_BOARD;
    
    public static MapBoard MAP_BOARD;
    
    public static MusicPlayer PLAYER = MusicPlayer.getInstance();
    
    private String userName;
    
    String filePath = "resources/Snake.Resources/track_1.wav";
    
    static boolean isPlaying = true;
   
    /**
     * Creates new form SnakeGameMainMenu
     */
    public SnakeGameMainMenu() {
        
        initComponents();
        
       
        PLAYER.loadMusic(filePath);
        
        PLAYER.clip.start();
        
        PLAYER.clip.loop(Clip.LOOP_CONTINUOUSLY);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        mapsButton = new javax.swing.JButton();
        optionsButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1600, 800));
        getContentPane().setLayout(null);

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/snakebackbutton.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setFocusPainted(false);
        backButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/snakebackbutton_rollover.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(30, 30, 70, 70);

        mapsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/snake_maps.png"))); // NOI18N
        mapsButton.setBorder(null);
        mapsButton.setBorderPainted(false);
        mapsButton.setContentAreaFilled(false);
        mapsButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/snake_maps_rollover.png"))); // NOI18N
        mapsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mapsButton);
        mapsButton.setBounds(920, 510, 170, 70);

        optionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/snake_options.png"))); // NOI18N
        optionsButton.setBorder(null);
        optionsButton.setBorderPainted(false);
        optionsButton.setContentAreaFilled(false);
        optionsButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/snake_options_rollover.png"))); // NOI18N
        optionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(optionsButton);
        optionsButton.setBounds(730, 510, 170, 70);

        startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/snake_start.png"))); // NOI18N
        startButton.setBorder(null);
        startButton.setBorderPainted(false);
        startButton.setContentAreaFilled(false);
        startButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/snake_start_rollover.png"))); // NOI18N
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startButton);
        startButton.setBounds(530, 510, 170, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/snakeGif.gif"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1600, 800);
        background.getAccessibleContext().setAccessibleName("Background");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void optionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsButtonActionPerformed
        // TODO add your handling code here:
        new Options().setVisible(true);

    }//GEN-LAST:event_optionsButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        SNAKE_BOARD = new SnakeBoard();
        SNAKE_BOARD.setVisible(true);
        if(States.TUTORIAL_GAME == 0){
            JOptionPane.showMessageDialog(null, "Use arrow keys to move!\nPress ESC to go back");
            States.TUTORIAL_GAME++;
        }

        setVisible(false);
    }//GEN-LAST:event_startButtonActionPerformed

    private void mapsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapsButtonActionPerformed
        MAP_BOARD = new MapBoard();
        MAP_BOARD.setVisible(true);
         if(States.TUTORIAL_MAP == 0){
            JOptionPane.showMessageDialog(null, "Use arrow keys to move the green square!\nPress SPACE to add a wall and press BACKSPACE to remove a wall\nPress ESC to save changes and go back");
            States.TUTORIAL_MAP++;
        }
        
        setVisible(false);
    }//GEN-LAST:event_mapsButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        //returning to user screen
        new UserScreen(userName).setVisible(true);
        UserScreen.SNAKE_GAME_MAIN_MENU.dispose();
        System.out.println("Backbutton Pressed");
        if (SNAKE_BOARD != null){
            SNAKE_BOARD.dispose();
        }
        PLAYER.clip.stop();
        PLAYER.clip.close();
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    public void setName(String userName){
        this.userName = userName;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnakeGameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnakeGameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnakeGameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnakeGameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnakeGameMainMenu().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton mapsButton;
    private javax.swing.JButton optionsButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
