/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import SnakeGame.boards.SnakeBoard;
import JFrame.Symbol;
import Libs.ColorEx;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import weka.datagenerators.Test;

/**
 *
 * @author AST
 */
public class UserScreen extends javax.swing.JFrame implements Runnable {

    String userName;

    //static variable declared to get instance
    public static SnakeGameMainMenu SNAKE_GAME_MAIN_MENU;
    private CurrencyConverterFrame cf;
    Thread t;
    JDialog jop = new JDialog();

    public UserScreen() {
        initComponents();
        ImageIcon icon = new ImageIcon(UserScreen.this.getClass().getResource("/Userscreen/user_screen.gif"));
        backgroundLabel.setIcon(icon);

        gamesLabel.setVisible(false);
        tictactoeButton.setVisible(false);
        hangmanButton.setVisible(false);
        snakeButton.setVisible(false);
        currencyConverterButton.setVisible(false);
        jLabelWelcome.setForeground(ColorEx.TRANSPARENT);
        jLabelWelcome.setVisible(false);
        jButtonSignOut.setVisible(false);

        Timer timer = new Timer(3000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {

                ImageIcon icon = new ImageIcon(UserScreen.this.getClass().getResource("/Userscreen/user_screen_2.gif"));
                backgroundLabel.setIcon(icon);

                gamesLabel.setVisible(true);
                tictactoeButton.setVisible(true);
                hangmanButton.setVisible(true);
                snakeButton.setVisible(true);
                currencyConverterButton.setVisible(true);
                jLabelWelcome.setVisible(true);
                jButtonSignOut.setVisible(true);

            }
        });

        timer.setRepeats(false); // Only execute once
        timer.start();

    }

    public UserScreen(String userName) {
        initComponents();
        this.userName = userName;

        //setting welcome text for user
        jLabelWelcome.setText(jLabelWelcome.getText() + ' ' + userName);
        ImageIcon icon = new ImageIcon(UserScreen.this.getClass().getResource("/Userscreen/user_screen.gif"));
        backgroundLabel.setIcon(icon);

        gamesLabel.setVisible(false);
        tictactoeButton.setVisible(false);
        hangmanButton.setVisible(false);
        snakeButton.setVisible(false);
        currencyConverterButton.setVisible(false);
        jLabelWelcome.setForeground(ColorEx.TRANSPARENT);
        jLabelWelcome.setVisible(false);
        jButtonSignOut.setVisible(false);

        Timer timer = new Timer(3000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {

                ImageIcon icon = new ImageIcon(UserScreen.this.getClass().getResource("/Userscreen/user_screen_2.gif"));
                backgroundLabel.setIcon(icon);

                gamesLabel.setVisible(true);
                tictactoeButton.setVisible(true);
                hangmanButton.setVisible(true);
                snakeButton.setVisible(true);
                currencyConverterButton.setVisible(true);
                jLabelWelcome.setVisible(true);
                jButtonSignOut.setVisible(true);

            }
        });

        timer.setRepeats(false); // Only execute once
        timer.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        gamesLabel = new javax.swing.JLabel();
        currencyConverterButton = new javax.swing.JButton();
        snakeButton = new javax.swing.JButton();
        hangmanButton = new javax.swing.JButton();
        tictactoeButton = new javax.swing.JButton();
        jLabelWelcome = new javax.swing.JLabel();
        jButtonSignOut = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(300, 200));
        jDialog1.getContentPane().setLayout(null);
        jDialog1.getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 330, 54);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(cancelButton);
        cancelButton.setBounds(100, 110, 80, 23);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1320, 900));
        setPreferredSize(new java.awt.Dimension(1320, 900));
        setSize(new java.awt.Dimension(1320, 900));
        getContentPane().setLayout(null);

        gamesLabel.setFont(new java.awt.Font("Kiona", 0, 24)); // NOI18N
        gamesLabel.setForeground(new java.awt.Color(255, 255, 255));
        gamesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/games.png"))); // NOI18N
        getContentPane().add(gamesLabel);
        gamesLabel.setBounds(580, 140, 153, 44);

        currencyConverterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/currency.png"))); // NOI18N
        currencyConverterButton.setBorder(null);
        currencyConverterButton.setBorderPainted(false);
        currencyConverterButton.setContentAreaFilled(false);
        currencyConverterButton.setFocusPainted(false);
        currencyConverterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyConverterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(currencyConverterButton);
        currencyConverterButton.setBounds(1090, 790, 138, 36);

        snakeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/snake.png"))); // NOI18N
        snakeButton.setBorder(null);
        snakeButton.setBorderPainted(false);
        snakeButton.setContentAreaFilled(false);
        snakeButton.setFocusPainted(false);
        snakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snakeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(snakeButton);
        snakeButton.setBounds(540, 370, 155, 33);

        hangmanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/hangman.png"))); // NOI18N
        hangmanButton.setBorder(null);
        hangmanButton.setBorderPainted(false);
        hangmanButton.setContentAreaFilled(false);
        hangmanButton.setFocusPainted(false);
        hangmanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hangmanButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hangmanButton);
        hangmanButton.setBounds(540, 300, 207, 33);

        tictactoeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/tictactoe.png"))); // NOI18N
        tictactoeButton.setBorder(null);
        tictactoeButton.setBorderPainted(false);
        tictactoeButton.setContentAreaFilled(false);
        tictactoeButton.setFocusPainted(false);
        tictactoeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tictactoeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tictactoeButton);
        tictactoeButton.setBounds(540, 230, 253, 33);

        jLabelWelcome.setFont(new java.awt.Font("Kiona", 0, 36)); // NOI18N
        jLabelWelcome.setText("Welcome");
        getContentPane().add(jLabelWelcome);
        jLabelWelcome.setBounds(80, 770, 562, 86);

        jButtonSignOut.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButtonSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/signout.png"))); // NOI18N
        jButtonSignOut.setBorder(null);
        jButtonSignOut.setBorderPainted(false);
        jButtonSignOut.setContentAreaFilled(false);
        jButtonSignOut.setFocusPainted(false);
        jButtonSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSignOut);
        jButtonSignOut.setBounds(1060, 140, 158, 26);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/user_screen_once.gif"))); // NOI18N
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 1320, 900);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignOutActionPerformed
        dispose();
        try {
            FileWriter writer = new FileWriter("resources/Status/id.txt");
            FileWriter writer2 = new FileWriter("resources/Status/cache.txt");
            //clearing user status from cache
            writer.write("");
            writer2.write("");
            //closing writer
            writer.close();
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(UserScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        new LoginScreen().setVisible(true);
    }//GEN-LAST:event_jButtonSignOutActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        // TODO add your handling code here:
        t.stop();
        jDialog1.dispose();

    }//GEN-LAST:event_cancelButtonActionPerformed

    private void tictactoeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tictactoeButtonActionPerformed
        // TODO add your handling code here: 
        dispose();
        new Symbol(userName).setVisible(true);

    }//GEN-LAST:event_tictactoeButtonActionPerformed

    private void hangmanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hangmanButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new HangManGame(userName).setVisible(true);
    }//GEN-LAST:event_hangmanButtonActionPerformed

    private void snakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snakeButtonActionPerformed
        // TODO add your handling code here:
        dispose();

        SNAKE_GAME_MAIN_MENU = new SnakeGameMainMenu();
        SNAKE_GAME_MAIN_MENU.setName(userName);
        //moving to next JFrame
        SNAKE_GAME_MAIN_MENU.setVisible(true);
    }//GEN-LAST:event_snakeButtonActionPerformed

    private void currencyConverterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyConverterButtonActionPerformed
        // TODO add your handling code here:

        t = new Thread(this, "opening converter");
        t.start();
        jDialog1.setVisible(true);
        jLabel1.setText("<html>Fetching converter data from the internet!<br/>Please wait...</html>");

        jDialog1.setLocationRelativeTo(null);
    }//GEN-LAST:event_currencyConverterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserScreen us = new UserScreen();
                us.setVisible(true);
                us.requestFocusInWindow();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton currencyConverterButton;
    private javax.swing.JLabel gamesLabel;
    private javax.swing.JButton hangmanButton;
    private javax.swing.JButton jButtonSignOut;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JButton snakeButton;
    private javax.swing.JButton tictactoeButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        cf = new CurrencyConverterFrame();
        cf.setVisible(true);

        jDialog1.setVisible(false);
    }
}
